import os
from typing import Optional

import numpy as np
from PIL import Image
from PySide6.QtCore import Qt
from PySide6.QtGui import QImage, QPixmap
from PySide6.QtWidgets import QWidget, QHBoxLayout, QLabel, QFileDialog
from qfluentwidgets import PushSettingCard, PushButton, PrimaryPushButton, InfoBar, FluentIcon as FIF

from src.utils.appconfig import cfg
from src.utils.dds_utils import load_image, save_image
from src.utils.filesystem_utils import get_app_root
from src.utils.helpers import BaseWidget
from src.utils.icons import CustomIcons
from src.utils.logging_utils import logger
from src.utils.palette_utils import (
    apply_palette_to_greyscale,
    build_palette_row_from_recolor,
    load_island_npz,
)


class AddToPaletteWidget(BaseWidget):
    """Generate new palette rows from recolored textures using saved islands."""

    def __init__(self, parent: Optional[QWidget], text: str = "Add To Palette"):
        super().__init__(parent=parent, text=text, vertical=True)

        # State
        self.npz_path: Optional[str] = None
        self.npz_metadata = None
        self.mask_stack: Optional[np.ndarray] = None
        self.islands: list = []
        self.palette_size: int = int(cfg.get(cfg.ci_default_palette_size)) if hasattr(cfg, "ci_default_palette_size") else 256
        self.grey_img: Optional[Image.Image] = None
        self.grey_path: Optional[str] = None
        self.recolor_img: Optional[Image.Image] = None
        self.recolor_path: Optional[str] = None
        self.palette_row: Optional[np.ndarray] = None
        self.palette_target_path: Optional[str] = None

        # File pickers
        self.npz_card = PushSettingCard(
            self.tr("Palette Islands NPZ"),
            CustomIcons.LAYER.icon() if hasattr(CustomIcons, "LAYER") else FIF.FOLDER,
            self.tr("Select saved islands (.npz)"),
            self.tr("No NPZ selected"),
        )
        self.npz_card.clicked.connect(self.on_select_npz)

        self.grey_card = PushSettingCard(
            self.tr("Greyscale Atlas"),
            CustomIcons.GREYSCALE.icon() if hasattr(CustomIcons, "GREYSCALE") else FIF.IMAGE,
            self.tr("Greyscale image generated by Palette Creator"),
            self.tr("No greyscale selected"),
        )
        self.grey_card.clicked.connect(self.on_select_greyscale)

        self.recolor_card = PushSettingCard(
            self.tr("Recolored Image"),
            CustomIcons.IMAGE_CIRCLE.icon(stroke=True) if hasattr(CustomIcons, "IMAGE_CIRCLE") else FIF.COLOR,
            self.tr("Updated colored texture matching the original"),
            self.tr("No recolor selected"),
        )
        self.recolor_card.clicked.connect(self.on_select_recolor)

        self.palette_card = PushSettingCard(
            self.tr("Existing Palette (optional)"),
            CustomIcons.PALETTE_2.icon(stroke=True),
            self.tr("Select palette to append the new row"),
            self.tr("No palette selected"),
        )
        self.palette_card.clicked.connect(self.on_select_palette_target)

        self.addToFrame(self.npz_card)
        self.addToFrame(self.grey_card)
        self.addToFrame(self.recolor_card)
        self.addToFrame(self.palette_card)

        # Preview area
        preview_container = QWidget()
        preview_layout = QHBoxLayout(preview_container)

        self.row_preview = QLabel()
        self.row_preview.setAlignment(Qt.AlignCenter)
        self.row_preview.setMinimumHeight(60)
        self.row_preview.setStyleSheet("background-color: #111; border: 1px solid #333;")
        preview_layout.addWidget(self.row_preview, 1)

        self.apply_preview = QLabel()
        self.apply_preview.setAlignment(Qt.AlignCenter)
        self.apply_preview.setMinimumSize(320, 320)
        self.apply_preview.setStyleSheet("background-color: #111; border: 1px solid #333;")
        preview_layout.addWidget(self.apply_preview, 2)

        self.addToFrame(preview_container)

        # Actions
        btn_row = QHBoxLayout()
        self.generate_btn = PrimaryPushButton(self.tr("Generate Palette Row"))
        self.generate_btn.clicked.connect(self.on_generate)
        btn_row.addWidget(self.generate_btn)

        self.save_row_btn = PushButton(self.tr("Save Row as Image"))
        self.save_row_btn.clicked.connect(self.on_save_row)
        btn_row.addWidget(self.save_row_btn)

        self.append_btn = PushButton(self.tr("Append Row to Palette"))
        self.append_btn.clicked.connect(self.on_append_palette)
        btn_row.addWidget(self.append_btn)

        action_box = QWidget()
        action_box.setLayout(btn_row)
        self.addToFrame(action_box)

    # ---------- File pickers ----------
    def on_select_npz(self):
        default_dir = os.path.join(get_app_root(), "npz")
        try:
            os.makedirs(default_dir, exist_ok=True)
        except Exception:
            default_dir = ""

        path, _ = QFileDialog.getOpenFileName(
            self,
            self.tr("Select Islands NPZ"),
            default_dir,
            "Palette Islands (*.npz);;All Files (*)",
        )
        if not path:
            return

        try:
            meta, masks, islands = load_island_npz(path)
            self.npz_path = path
            self.npz_metadata = meta
            self.mask_stack = masks
            self.islands = islands
            # Derive palette size from islands
            if self.islands:
                self.palette_size = max(ge for _, _, ge in self.islands) + 1
            self.npz_card.setContent(f"{os.path.basename(path)} | {len(islands)} islands")
            self._validate_dimensions()
        except Exception as e:
            logger.exception("Failed to load NPZ: %s", e)
            InfoBar.error(
                title=self.tr("Error"),
                content=self.tr(f"Failed to load NPZ: {str(e)}"),
                duration=5000,
                parent=self,
            )

    def on_select_greyscale(self):
        path, _ = QFileDialog.getOpenFileName(
            self,
            self.tr("Select Greyscale"),
            "",
            self.tr("Images (*.png *.jpg *.jpeg *.bmp *.tga *.webp *.dds)"),
        )
        if not path:
            return
        try:
            img = load_image(path, f="L")
            self.grey_img = img.convert("L")
            self.grey_path = path
            self.grey_card.setContent(f"{os.path.basename(path)} | {img.size[0]}x{img.size[1]} (L)")
            self._validate_dimensions()
        except Exception as e:
            logger.exception("Failed to load greyscale: %s", e)
            InfoBar.error(
                title=self.tr("Error"),
                content=self.tr(f"Failed to load greyscale: {str(e)}"),
                duration=4000,
                parent=self,
            )

    def on_select_recolor(self):
        path, _ = QFileDialog.getOpenFileName(
            self,
            self.tr("Select Recolored Image"),
            "",
            self.tr("Images (*.png *.jpg *.jpeg *.bmp *.tga *.webp *.dds)"),
        )
        if not path:
            return
        try:
            img = load_image(path)
            self.recolor_img = img.convert("RGBA")
            self.recolor_path = path
            self.recolor_card.setContent(f"{os.path.basename(path)} | {img.size[0]}x{img.size[1]}")
            self._validate_dimensions()
        except Exception as e:
            logger.exception("Failed to load recolor: %s", e)
            InfoBar.error(
                title=self.tr("Error"),
                content=self.tr(f"Failed to load recolored image: {str(e)}"),
                duration=4000,
                parent=self,
            )

    def on_select_palette_target(self):
        path, _ = QFileDialog.getOpenFileName(
            self,
            self.tr("Select Palette"),
            "",
            self.tr("Images (*.png *.jpg *.jpeg *.bmp *.tga *.webp *.dds)"),
        )
        if not path:
            return
        try:
            img = load_image(path)
            w, h = img.size
            self.palette_target_path = path
            self.palette_card.setContent(f"{os.path.basename(path)} | {w}x{h}")
        except Exception as e:
            logger.exception("Failed to read palette: %s", e)
            InfoBar.error(
                title=self.tr("Error"),
                content=self.tr(f"Failed to open palette: {str(e)}"),
                duration=4000,
                parent=self,
            )

    # ---------- Core logic ----------
    def _validate_dimensions(self):
        if self.npz_metadata is None:
            return
        target_w = int(self.npz_metadata.get("width", 0))
        target_h = int(self.npz_metadata.get("height", 0))
        if self.grey_img and self.grey_img.size != (target_w, target_h):
            InfoBar.warning(
                title=self.tr("Size Mismatch"),
                content=self.tr("Greyscale dimensions do not match saved islands."),
                duration=4000,
                parent=self,
            )
        if self.recolor_img and self.recolor_img.size != (target_w, target_h):
            InfoBar.warning(
                title=self.tr("Size Mismatch"),
                content=self.tr("Recolored image dimensions do not match saved islands."),
                duration=4000,
                parent=self,
            )

    def on_generate(self):
        if self.npz_metadata is None or self.mask_stack is None or not self.islands:
            InfoBar.warning(
                title=self.tr("Islands Required"),
                content=self.tr("Load a palette islands NPZ first."),
                duration=3000,
                parent=self,
            )
            return
        if self.grey_img is None or self.recolor_img is None:
            InfoBar.warning(
                title=self.tr("Images Required"),
                content=self.tr("Select both greyscale and recolored images."),
                duration=3000,
                parent=self,
            )
            return
        target_w = int(self.npz_metadata.get("width", 0)) if self.npz_metadata else 0
        target_h = int(self.npz_metadata.get("height", 0)) if self.npz_metadata else 0
        if self.grey_img and self.grey_img.size != (target_w, target_h):
            InfoBar.error(
                title=self.tr("Size Mismatch"),
                content=self.tr("Greyscale size does not match islands metadata."),
                duration=4000,
                parent=self,
            )
            return
        if self.recolor_img and self.recolor_img.size != (target_w, target_h):
            InfoBar.error(
                title=self.tr("Size Mismatch"),
                content=self.tr("Recolored image size does not match islands metadata."),
                duration=4000,
                parent=self,
            )
            return
        try:
            row = build_palette_row_from_recolor(
                self.grey_img,
                self.recolor_img,
                self.islands,
                self.mask_stack,
                self.palette_size,
            )
            self.palette_row = row
            self._set_row_preview(row)
            self._update_apply_preview()
            InfoBar.success(
                title=self.tr("Row Generated"),
                content=self.tr("Palette row built from recolored image."),
                duration=3000,
                parent=self,
            )
        except Exception as e:
            logger.exception("Failed to generate palette row: %s", e)
            InfoBar.error(
                title=self.tr("Generation Failed"),
                content=self.tr(f"Could not build palette row: {str(e)}"),
                duration=5000,
                parent=self,
            )

    def on_save_row(self):
        if self.palette_row is None:
            return
        base_dir = ""
        if self.recolor_path:
            base_dir = os.path.dirname(self.recolor_path)
        path, _ = QFileDialog.getSaveFileName(
            self,
            self.tr("Save Palette Row"),
            base_dir,
            self.tr("PNG Image (*.png);;DDS Image (*.dds);;All Files (*)"),
        )
        if not path:
            return
        try:
            row_height = int(cfg.get(cfg.ci_palette_row_height)) if hasattr(cfg, "ci_palette_row_height") else 4
            row_block = np.repeat(self.palette_row[np.newaxis, :, :], row_height, axis=0)
            img = Image.fromarray(row_block, mode="RGB")
            save_image(img, path, True)
            InfoBar.success(
                title=self.tr("Saved"),
                content=self.tr(f"Palette row saved to:\n{path}"),
                duration=3000,
                parent=self,
            )
        except Exception as e:
            logger.exception("Failed to save row: %s", e)
            InfoBar.error(
                title=self.tr("Save Failed"),
                content=self.tr(f"Could not save row: {str(e)}"),
                duration=4000,
                parent=self,
            )

    def on_append_palette(self):
        if self.palette_row is None:
            InfoBar.warning(
                title=self.tr("No Row"),
                content=self.tr("Generate a palette row first."),
                duration=3000,
                parent=self,
            )
            return

        if not self.palette_target_path:
            self.on_select_palette_target()
            if not self.palette_target_path:
                return

        try:
            pal_img = load_image(self.palette_target_path)
            pal_arr = np.array(pal_img.convert("RGBA"), dtype=np.uint8)
            h, w, c = pal_arr.shape
            if w != self.palette_row.shape[0]:
                raise ValueError(self.tr("Palette width does not match generated row."))

            row_height = int(cfg.get(cfg.ci_palette_row_height)) if hasattr(cfg, "ci_palette_row_height") else 4
            row_block = np.zeros((row_height, w, 4), dtype=np.uint8)
            row_block[:, :, :3] = self.palette_row[np.newaxis, :, :]
            row_block[:, :, 3] = 255

            new_arr = np.concatenate([pal_arr, row_block], axis=0)
            mode = "RGBA"
            new_img = Image.fromarray(new_arr, mode=mode)
            save_image(new_img, self.palette_target_path, True)
            self.palette_card.setContent(f"{os.path.basename(self.palette_target_path)} | {w}x{h + row_height}")
            InfoBar.success(
                title=self.tr("Palette Updated"),
                content=self.tr("Row appended to palette."),
                duration=3000,
                parent=self,
            )
        except Exception as e:
            logger.exception("Failed to append palette: %s", e)
            InfoBar.error(
                title=self.tr("Append Failed"),
                content=self.tr(f"Could not append row: {str(e)}"),
                duration=4000,
                parent=self,
            )

    # ---------- Previews ----------
    def _set_row_preview(self, row: np.ndarray):
        if row is None or row.size == 0:
            self.row_preview.clear()
            return
        row_height = max(16, int(cfg.get(cfg.ci_palette_row_height)) if hasattr(cfg, "ci_palette_row_height") else 4)
        preview = np.repeat(row[np.newaxis, :, :], row_height, axis=0)
        qimg = self._array_to_qimage(preview)
        pix = QPixmap.fromImage(qimg).scaled(self.row_preview.width() or preview.shape[1], row_height, Qt.KeepAspectRatio, Qt.SmoothTransformation)
        self.row_preview.setPixmap(pix)

    def _update_apply_preview(self):
        if self.palette_row is None or self.grey_img is None:
            self.apply_preview.clear()
            return
        palette_img = Image.fromarray(self.palette_row[np.newaxis, :, :], mode="RGB")
        preview = apply_palette_to_greyscale(palette_img, self.grey_img, self.palette_row)
        arr = np.array(preview.convert("RGBA"), dtype=np.uint8)
        qimg = self._array_to_qimage(arr)
        pix = QPixmap.fromImage(qimg).scaled(
            max(1, self.apply_preview.width()),
            max(1, self.apply_preview.height()),
            Qt.KeepAspectRatio,
            Qt.SmoothTransformation,
        )
        self.apply_preview.setPixmap(pix)

    @staticmethod
    def _array_to_qimage(arr: np.ndarray) -> QImage:
        if arr.ndim != 3:
            raise ValueError("Expected HxWxC array")
        h, w, c = arr.shape
        if c == 3:
            fmt = QImage.Format.Format_RGB888
        else:
            fmt = QImage.Format.Format_RGBA8888
        return QImage(arr.data, w, h, arr.strides[0], fmt)